-- TrafficConeGod

return function(Sunshine, entity)
    -- local prefab = entity.prefab
    -- if prefab then
    --     prefab.dataPrefab = require(prefab.prefab)
    --     for componentName, dataComponent in pairs(prefab.dataPrefab) do
    --         if componentName ~= "core" and not entity[componentName] then
    --             local componentInterface = Sunshine.componentInterfaces[componentName]
    --             if componentInterface then
    --                 local component = { objectType = "Component" }
    --                 Sunshine:createMetatable(component, componentInterface, componentName)
    --                 for name, value in pairs(dataComponent) do
    --                     component[name] = value
    --                 end
                    -- for name, value in pairs(dataComponent) do
                    --     if not component[name] then
                    --         component[name] = value
                    --     end
                    -- end
    --                 for name, propertyInterface in pairs(componentInterface) do
    --                     if not component[name] then
    --                         component[name] = propertyInterface.default
    --                     end
    --                 end
    --                 entity[componentName] = component
    --             else
    --                 error("Component " .. componentName .. " does not exist.")
    --             end
    --         end
    --     end
    --     if prefab.dataPrefab.core then
    --         entity.core.id = prefab.dataPrefab.core.id
    --     end
    --     entity.core.active = true
    -- end
end